# constants.py - Greatly expanded with many more constants and enums
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60
PLAYER_SPEED = 5
ENEMY_SPEED = 3
BULLET_SPEED = 7
POWERUP_SPEED = 2
PARTICLE_LIFETIME = 30
EXPLOSION_PARTICLES = 20
BOSS_HEALTH = 100
MINI_BOSS_HEALTH = 50
PLAYER_HEALTH = 5
SHIELD_DURATION = 5000  # ms
SPEED_BOOST_DURATION = 10000
WEAPON_UPGRADE_DURATION = 15000
DIFFICULTY_EASY = 0.8
DIFFICULTY_NORMAL = 1.0
DIFFICULTY_HARD = 1.2
STAR_SPEED = 2
GRAVITY = 0.5
MAX_LEVEL = 20  # Increased for more content
SCORE_MULTIPLIER = 1.5
MAX_WAVES_PER_LEVEL = 5
ENEMY_SPAWN_RATE = 0.05
POWERUP_SPAWN_RATE = 0.01
BOSS_PHASE_THRESHOLD = 0.5  # Health percentage for phase change
INVINCIBILITY_DURATION = 2000
MULTIPLAYER_PORT = 5555  # Placeholder
LOG_LEVEL_DEBUG = 0
LOG_LEVEL_INFO = 1
LOG_LEVEL_ERROR = 2
COLOR_BLACK = (0, 0, 0)
COLOR_WHITE = (255, 255, 255)
COLOR_RED = (255, 0, 0)
COLOR_GREEN = (0, 255, 0)
COLOR_BLUE = (0, 0, 255)
COLOR_YELLOW = (255, 255, 0)
COLOR_PURPLE = (255, 0, 255)
COLOR_CYAN = (0, 255, 255)
COLOR_ORANGE = (255, 165, 0)
# Add enums if needed
from enum import Enum
class GameState(Enum):
    MENU = 1
    PLAYING = 2
    PAUSED = 3
    GAME_OVER = 4
    SETTINGS = 5
    HIGHSCORES = 6
class Difficulty(Enum):
    EASY = DIFFICULTY_EASY
    NORMAL = DIFFICULTY_NORMAL
    HARD = DIFFICULTY_HARD
# Many more constants for expansion
MAX_PARTICLES = 1000
MINI_MAP_SCALE = 0.2
HUD_HEIGHT = 50
MENU_FONT_SIZE = 50
SMALL_FONT_SIZE = 24
# Sound volumes
SOUND_VOLUME_MAX = 1.0
MUSIC_VOLUME_MAX = 0.8
# Animation frames
ANIMATION_FRAME_RATE = 10
# AI parameters
AI_AGGRESSION_LOW = 0.5
AI_AGGRESSION_HIGH = 1.5
# Etc.
